### ISSUE TITLE
undefined is not handled

### ISSUE THREAD

**Issue by Skalkaz** [olado/doT#212]
template method (line 92 in doT.js) should handle the input undefined.

Track:
TypeError: Cannot read property 'toString' of undefined
at resolveDefs (/app/node_modules/dot/doT.js:54:54) 
at Object.doT.template (/app/node_modules/dot/doT.js:92:33)

**Comment by epoberezkin** [comment]
@Skalkaz can you please post your template/code? It's not quite clear what exactly fails. It also seems to me you may be not using the latest version...

**Comment by Skalkaz** [comment]
"version": "1.0.3"

line 53 and 54 of doT.js
	function resolveDefs(c, block, def) {
		return ((typeof block === "string") ? block : block.toString())
This causes an error if block is undefined.

line 89 of doT.js
doT.template = function(tmpl, c, def) { 
tmpl is undefined, this causes the error.

I used the dot.js as:
html = dot.template(page)({link: "http://sas.com"})
But page was undefined by accidently.

**Comment by epoberezkin** [comment]
I see. The latest version is 1.1.1, that's why I was confused about the line numbers.

I guess the idea is that template compilation is a build / bootstrapping time, rather than app run time, so it's ok to throw exception during that phase. If you're compiling the template at the same time you need to render the page (as in your example) then you're losing the main doT advantage - speed.

I don't think it needs any improvement to be honest. Only render time undefineds should be handled, not template compilation undefineds.

**Comment by Skalkaz** [comment]
Okey, thanks, feel free to close the issue.
